### ISSUE TITLE
Cannot run `ranger`

### ISSUE THREAD

**Issue by cwrau** [kspi/dmenu-frecency#20]
I'm running arch (manjaro)

I cannot launch `ranger` (installed from the community repo)
It crashes everytime:
```
Traceback (most recent call last):
  File "/usr/bin/ranger", line 36, in <module>
    sys.exit(ranger.main())  # pylint: disable=no-member
  File "/usr/lib/python3.7/site-packages/ranger/core/main.py", line 225, in main
    fm.ui.destroy()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 188, in destroy
    self.suspend()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 140, in suspend
    curses.nocbreak()
_curses.error: nocbreak() returned ERR
```

Launching it via `i3-dmenu-desktop` works fine

Is this a problem with how this launcher tries to launch `ranger`, or with `ranger` itself?

**Comment by elig0n** [comment]
If i'm not mistaken this is due to ranger being a terminal application and so it is trying to communicate with a non existent terminal. dmenu-frecency runs .desktop applications and does not allow to run terminal commands like i3 dmenu. A version for launching all applications which will also allow executing commands in a terminal is requested
